### ISSUE TITLE
There is no consideration for the dark theme availalble with Chrom DevTools

### ISSUE THREAD

**Issue by nz-chris** [wizzyfx/nerdeFocusPlugIn#1]
Dark text on a dark background makes for very difficult use of this very useful extension.
![image](https://user-images.githubusercontent.com/37297133/58446479-fb9b3680-8154-11e9-93d4-a8dbf84b58d3.png)

**Comment by wizzyfx** [comment]
Great catch! I'll release a fix for that, and make sure to test in Dark theme before future releases.

**Comment by wizzyfx** [comment]
Fixed.. Should be updated on Chrome Store in a couple of hours.
